/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

import br.univali.ps.ui.swing.Themeable;

/**
 *
 * @author Adson Esteves
 */
public class TelaRelatarBug extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form TelaRelatarBug
     */
    public TelaRelatarBug() {
        initComponents();
        configurarCores();
    }
    
    @Override
    public void configurarCores() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        painelIssue = new javax.swing.JPanel();
        painelTxtIssue = new javax.swing.JPanel();
        painelTitleIssue = new javax.swing.JPanel();
        labelTitleIssue = new javax.swing.JLabel();
        painelDescIssue = new javax.swing.JPanel();
        labelDescIssue = new javax.swing.JLabel();
        painelBotaoIssue = new javax.swing.JPanel();
        webButton2 = new com.alee.laf.button.WebButton();
        paineInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDiscord = new javax.swing.JLabel();
        labelFacebook = new javax.swing.JLabel();
        labelGmail = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(773, 382));
        setLayout(new java.awt.BorderLayout());

        mainpanel.setLayout(new java.awt.BorderLayout());

        painelIssue.setLayout(new java.awt.BorderLayout());

        painelTxtIssue.setLayout(new java.awt.BorderLayout());

        labelTitleIssue.setText("Issue");

        javax.swing.GroupLayout painelTitleIssueLayout = new javax.swing.GroupLayout(painelTitleIssue);
        painelTitleIssue.setLayout(painelTitleIssueLayout);
        painelTitleIssueLayout.setHorizontalGroup(
            painelTitleIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTitleIssueLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(labelTitleIssue)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        painelTitleIssueLayout.setVerticalGroup(
            painelTitleIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTitleIssueLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelTitleIssue)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        painelTxtIssue.add(painelTitleIssue, java.awt.BorderLayout.NORTH);

        labelDescIssue.setText("Para issoblablablablablablablablablablablablablabla");

        javax.swing.GroupLayout painelDescIssueLayout = new javax.swing.GroupLayout(painelDescIssue);
        painelDescIssue.setLayout(painelDescIssueLayout);
        painelDescIssueLayout.setHorizontalGroup(
            painelDescIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDescIssueLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelDescIssue))
        );
        painelDescIssueLayout.setVerticalGroup(
            painelDescIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDescIssueLayout.createSequentialGroup()
                .addComponent(labelDescIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelTxtIssue.add(painelDescIssue, java.awt.BorderLayout.CENTER);

        painelIssue.add(painelTxtIssue, java.awt.BorderLayout.WEST);

        webButton2.setText("webButton2");

        javax.swing.GroupLayout painelBotaoIssueLayout = new javax.swing.GroupLayout(painelBotaoIssue);
        painelBotaoIssue.setLayout(painelBotaoIssueLayout);
        painelBotaoIssueLayout.setHorizontalGroup(
            painelBotaoIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotaoIssueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(webButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelBotaoIssueLayout.setVerticalGroup(
            painelBotaoIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotaoIssueLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(webButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        painelIssue.add(painelBotaoIssue, java.awt.BorderLayout.EAST);

        mainpanel.add(painelIssue, java.awt.BorderLayout.CENTER);

        add(mainpanel, java.awt.BorderLayout.CENTER);

        paineInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Outras formas de contato:");
        paineInferior.add(jLabel1);

        labelDiscord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/discord.png"))); // NOI18N
        labelDiscord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelDiscord.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelDiscord);

        labelFacebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/fb.png"))); // NOI18N
        labelFacebook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFacebook.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelFacebook);

        labelGmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/gmail.png"))); // NOI18N
        labelGmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelGmail.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelGmail);

        add(paineInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDescIssue;
    private javax.swing.JLabel labelDiscord;
    private javax.swing.JLabel labelFacebook;
    private javax.swing.JLabel labelGmail;
    private javax.swing.JLabel labelTitleIssue;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel paineInferior;
    private javax.swing.JPanel painelBotaoIssue;
    private javax.swing.JPanel painelDescIssue;
    private javax.swing.JPanel painelIssue;
    private javax.swing.JPanel painelTitleIssue;
    private javax.swing.JPanel painelTxtIssue;
    private com.alee.laf.button.WebButton webButton2;
    // End of variables declaration//GEN-END:variables
    

}
