/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

/**
 *
 * @author LITE
 */
public class TelaDicas extends javax.swing.JFrame {

    /**
     * Creates new form TelaDicas
     */
    public TelaDicas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        carrouselPane = new javax.swing.JPanel();
        hintPane = new javax.swing.JPanel();
        imagePane = new javax.swing.JPanel();
        descriptionPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        optionPane = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainPanel.setLayout(new java.awt.BorderLayout(0, 15));

        carrouselPane.setLayout(new java.awt.BorderLayout());

        hintPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout imagePaneLayout = new javax.swing.GroupLayout(imagePane);
        imagePane.setLayout(imagePaneLayout);
        imagePaneLayout.setHorizontalGroup(
            imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        imagePaneLayout.setVerticalGroup(
            imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        hintPane.add(imagePane, java.awt.BorderLayout.CENTER);

        descriptionPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        descriptionPane.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Texto");
        descriptionPane.add(jLabel1, java.awt.BorderLayout.CENTER);

        hintPane.add(descriptionPane, java.awt.BorderLayout.SOUTH);

        carrouselPane.add(hintPane, java.awt.BorderLayout.CENTER);

        scrollPane.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Próximo");
        scrollPane.add(jButton1, java.awt.BorderLayout.EAST);

        jButton2.setText("Anterior");
        scrollPane.add(jButton2, java.awt.BorderLayout.WEST);

        carrouselPane.add(scrollPane, java.awt.BorderLayout.SOUTH);

        mainPanel.add(carrouselPane, java.awt.BorderLayout.CENTER);

        optionPane.setPreferredSize(new java.awt.Dimension(0, 30));
        optionPane.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("Não mostrar novamente");
        optionPane.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        jButton3.setText("Sair");
        optionPane.add(jButton3, java.awt.BorderLayout.EAST);
        optionPane.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        mainPanel.add(optionPane, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel carrouselPane;
    private javax.swing.JPanel descriptionPane;
    private javax.swing.JPanel hintPane;
    private javax.swing.JPanel imagePane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel optionPane;
    private javax.swing.JPanel scrollPane;
    // End of variables declaration//GEN-END:variables
}
