/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

/**
 *
 * @author Adson Esteves
 */
public class TelaExcecaoEncontrada extends javax.swing.JPanel {

    /**
     * Creates new form TelaExcecaoEncontrada
     */
    public TelaExcecaoEncontrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelExplicacao = new javax.swing.JPanel();
        erroTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        erroDesc = new javax.swing.JPanel();
        painelStackTrace = new javax.swing.JPanel();
        painelBotao = new javax.swing.JPanel();
        botaoAbrirStack = new com.alee.laf.button.WebButton();
        botaoCopiarErro = new com.alee.laf.button.WebButton();
        botaoReportarBug = new com.alee.laf.button.WebButton();
        scrollStackTrace = new javax.swing.JScrollPane();
        areaTextoStackTrace = new javax.swing.JTextArea();
        paineInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDiscord = new javax.swing.JLabel();
        labelFacebook = new javax.swing.JLabel();
        labelGmail = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        painelPrincipal.setLayout(new java.awt.BorderLayout());

        painelExplicacao.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Um erro desconhecido foi encontrado");

        javax.swing.GroupLayout erroTituloLayout = new javax.swing.GroupLayout(erroTitulo);
        erroTitulo.setLayout(erroTituloLayout);
        erroTituloLayout.setHorizontalGroup(
            erroTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erroTituloLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(106, 106, 106))
        );
        erroTituloLayout.setVerticalGroup(
            erroTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erroTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        painelExplicacao.add(erroTitulo, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout erroDescLayout = new javax.swing.GroupLayout(erroDesc);
        erroDesc.setLayout(erroDescLayout);
        erroDescLayout.setHorizontalGroup(
            erroDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        erroDescLayout.setVerticalGroup(
            erroDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        painelExplicacao.add(erroDesc, java.awt.BorderLayout.SOUTH);

        painelPrincipal.add(painelExplicacao, java.awt.BorderLayout.NORTH);

        painelStackTrace.setLayout(new java.awt.BorderLayout());

        painelBotao.setPreferredSize(new java.awt.Dimension(403, 30));

        botaoAbrirStack.setText("Mostrar Erros");

        botaoCopiarErro.setText("Copiar Erro");

        botaoReportarBug.setText("Reportar Erro");

        javax.swing.GroupLayout painelBotaoLayout = new javax.swing.GroupLayout(painelBotao);
        painelBotao.setLayout(painelBotaoLayout);
        painelBotaoLayout.setHorizontalGroup(
            painelBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botaoAbrirStack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(botaoCopiarErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(botaoReportarBug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        painelBotaoLayout.setVerticalGroup(
            painelBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botaoAbrirStack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoCopiarErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoReportarBug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelStackTrace.add(painelBotao, java.awt.BorderLayout.NORTH);

        areaTextoStackTrace.setColumns(20);
        areaTextoStackTrace.setRows(5);
        scrollStackTrace.setViewportView(areaTextoStackTrace);

        painelStackTrace.add(scrollStackTrace, java.awt.BorderLayout.SOUTH);

        painelPrincipal.add(painelStackTrace, java.awt.BorderLayout.CENTER);

        add(painelPrincipal, java.awt.BorderLayout.NORTH);

        paineInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Outras formas de contato:");
        paineInferior.add(jLabel1);

        labelDiscord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/discord.png"))); // NOI18N
        labelDiscord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelDiscord.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelDiscord);

        labelFacebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/fb.png"))); // NOI18N
        labelFacebook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFacebook.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelFacebook);

        labelGmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/gmail.png"))); // NOI18N
        labelGmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelGmail.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelGmail);

        add(paineInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoStackTrace;
    private com.alee.laf.button.WebButton botaoAbrirStack;
    private com.alee.laf.button.WebButton botaoCopiarErro;
    private com.alee.laf.button.WebButton botaoReportarBug;
    private javax.swing.JPanel erroDesc;
    private javax.swing.JPanel erroTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDiscord;
    private javax.swing.JLabel labelFacebook;
    private javax.swing.JLabel labelGmail;
    private javax.swing.JPanel paineInferior;
    private javax.swing.JPanel painelBotao;
    private javax.swing.JPanel painelExplicacao;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelStackTrace;
    private javax.swing.JScrollPane scrollStackTrace;
    // End of variables declaration//GEN-END:variables
}
