/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

import br.univali.ps.ui.swing.Themeable;

/**
 *
 * @author Adson Esteves
 */
public class TelaRelatarBug extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form TelaRelatarBug
     */
    public TelaRelatarBug() {
        initComponents();
        configurarCores();
    }
    
    @Override
    public void configurarCores() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        painelIssue = new javax.swing.JPanel();
        painelTxtIssue = new javax.swing.JPanel();
        painelTitleIssue = new javax.swing.JPanel();
        labelTitleIssue = new javax.swing.JLabel();
        painelDescIssue = new javax.swing.JPanel();
        labelDescIssue = new javax.swing.JLabel();
        painelBotaoIssue = new javax.swing.JPanel();
        webButton1 = new com.alee.laf.button.WebButton();
        painelDebug = new javax.swing.JPanel();
        painelTxtDebug = new javax.swing.JPanel();
        painelTitleDebug = new javax.swing.JPanel();
        labelTitleDebug = new javax.swing.JLabel();
        panielDescDebug = new javax.swing.JPanel();
        labelDescDebug = new javax.swing.JLabel();
        painelDebugBotao = new javax.swing.JPanel();
        webButton2 = new com.alee.laf.button.WebButton();
        paineInferior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDiscord = new javax.swing.JLabel();
        labelFacebook = new javax.swing.JLabel();
        labelGmail = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(773, 382));
        setLayout(new java.awt.BorderLayout());

        mainpanel.setLayout(new java.awt.BorderLayout());

        painelIssue.setLayout(new java.awt.BorderLayout());

        painelTxtIssue.setLayout(new java.awt.BorderLayout());

        labelTitleIssue.setText("Issue");
        painelTitleIssue.add(labelTitleIssue);

        painelTxtIssue.add(painelTitleIssue, java.awt.BorderLayout.NORTH);

        labelDescIssue.setText("Para issoblablablablablablablablablablablablablabla");
        painelDescIssue.add(labelDescIssue);

        painelTxtIssue.add(painelDescIssue, java.awt.BorderLayout.CENTER);

        painelIssue.add(painelTxtIssue, java.awt.BorderLayout.WEST);

        painelBotaoIssue.setLayout(new java.awt.BorderLayout());

        webButton1.setText("webButton1");
        painelBotaoIssue.add(webButton1, java.awt.BorderLayout.CENTER);

        painelIssue.add(painelBotaoIssue, java.awt.BorderLayout.EAST);

        mainpanel.add(painelIssue, java.awt.BorderLayout.NORTH);

        painelDebug.setLayout(new java.awt.BorderLayout());

        painelTxtDebug.setLayout(new java.awt.BorderLayout());

        labelTitleDebug.setText("Modo Debug");
        painelTitleDebug.add(labelTitleDebug);

        painelTxtDebug.add(painelTitleDebug, java.awt.BorderLayout.NORTH);

        labelDescDebug.setText("4 Dis lerolerolerolerolerolerolerolerolerolerolerolero");
        panielDescDebug.add(labelDescDebug);

        painelTxtDebug.add(panielDescDebug, java.awt.BorderLayout.SOUTH);

        painelDebug.add(painelTxtDebug, java.awt.BorderLayout.WEST);

        webButton2.setText("webButton2");
        painelDebugBotao.add(webButton2);

        painelDebug.add(painelDebugBotao, java.awt.BorderLayout.EAST);

        mainpanel.add(painelDebug, java.awt.BorderLayout.SOUTH);

        add(mainpanel, java.awt.BorderLayout.CENTER);

        paineInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Outras formas de contato:");
        paineInferior.add(jLabel1);

        labelDiscord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/discord.png"))); // NOI18N
        labelDiscord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelDiscord.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelDiscord);

        labelFacebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/fb.png"))); // NOI18N
        labelFacebook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFacebook.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelFacebook);

        labelGmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/gmail.png"))); // NOI18N
        labelGmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelGmail.setPreferredSize(new java.awt.Dimension(50, 50));
        paineInferior.add(labelGmail);

        add(paineInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDescDebug;
    private javax.swing.JLabel labelDescIssue;
    private javax.swing.JLabel labelDiscord;
    private javax.swing.JLabel labelFacebook;
    private javax.swing.JLabel labelGmail;
    private javax.swing.JLabel labelTitleDebug;
    private javax.swing.JLabel labelTitleIssue;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel paineInferior;
    private javax.swing.JPanel painelBotaoIssue;
    private javax.swing.JPanel painelDebug;
    private javax.swing.JPanel painelDebugBotao;
    private javax.swing.JPanel painelDescIssue;
    private javax.swing.JPanel painelIssue;
    private javax.swing.JPanel painelTitleDebug;
    private javax.swing.JPanel painelTitleIssue;
    private javax.swing.JPanel painelTxtDebug;
    private javax.swing.JPanel painelTxtIssue;
    private javax.swing.JPanel panielDescDebug;
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton2;
    // End of variables declaration//GEN-END:variables
    

}
