package br.univali.ps;

import br.univali.ps.nucleo.PortugolStudio;
import br.univali.ps.ui.PainelTabuladoPrincipal;
import br.univali.ps.ui.TelaPrincipal;
import java.awt.BorderLayout;
import java.io.File;
import java.util.List;
import javax.swing.UIManager;

/**
 *
 * @author Elieser
 */
public class PSApplet extends javax.swing.JApplet implements TelaPrincipal
{
    private final PainelTabuladoPrincipal painelTabulado = new PainelTabuladoPrincipal();

    static
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            //ex.printStackTrace();
        }
    }

    @Override
    public void init()
    {


        try
        {
            java.awt.EventQueue.invokeAndWait(new Runnable()
            {
                public void run()
                {


                    initComponents();

                    PortugolStudio portugol = PortugolStudio.getInstancia();
                    portugol.iniciar(null, PSApplet.this);
                    setLayout(new BorderLayout());
                    add(portugol.getTelaPrincipal().getPainelTabulado(), BorderLayout.CENTER);

                }
            });
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }



    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public PainelTabuladoPrincipal getPainelTabulado()
    {

        return painelTabulado;
    }

    @Override
    public void setArquivosIniciais(List<File> arquivos)
    {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
}
