package br.univali.ps;

import br.univali.portugol.corretor.dinamico.model.Questao;
import br.univali.ps.exception.CarregamentoDeExercicioException;
import br.univali.ps.nucleo.PortugolStudio;
import br.univali.ps.ui.abas.AbaCodigoFonte;
import br.univali.ps.ui.abas.AbaCodigoFonteDoApplet;
import java.awt.BorderLayout;
import java.io.IOException;
import java.net.MalformedURLException;
import javax.swing.UIManager;

/**
 *
 * @author Elieser
 */
public class TelaPrincipalApplet extends javax.swing.JApplet {

    private static final long serialVersionUID = 1L;
    private AbaCodigoFonte abaCodigoFonte;

    public TelaPrincipalApplet() {
        instalaLookAndFeel();
    }

    private void abreQuestao(final String urlDoPexDaQuestao) throws MalformedURLException, IOException {

        try {
            ParserDeQuestao parserDeQuestao = new ParserDeQuestaoParaDesktop();// new ParserDeQuestaoParaApplet();
            Questao questao = PortugolStudio.getInstancia().abrirQuestao(urlDoPexDaQuestao, parserDeQuestao);
            abaCodigoFonte.setQuestao(questao);

        } catch (CarregamentoDeExercicioException ex) {
            PortugolStudio.getInstancia().getTratadorExcecoes().exibirExcecao(ex);
        }

    }

//    private boolean recebeuOsParametros() {
//        String idDaQuestao = getParameter("idDaQuestao");
//        String idDoAluno = getParameter("idDoAluno");
//        return idDaQuestao != null && !idDaQuestao.isEmpty() && idDoAluno != null && !idDoAluno.isEmpty();
//    }
    private void carregaExercicio() {
        int idDaQuestao = getIdDaQuestao();
        AppletUtils.exibeMensagemNaConsoleJava("O applet recebeu o id da questão " + idDaQuestao);
        try {
            String caminhoBaseDosExercicios = "http://localhost:8084/exercicios";
            //String caminhoBaseDosExercicios = getCodeBase() + getParameter("pathDosExercicios");
            if (caminhoBaseDosExercicios == null) {
                throw new IllegalArgumentException("O caminho base dos exercícios não foi passado como parâmetro para o applet!");
            }
            String urlDoExercicio = AppletUtils.getCaminhoDoArquivoDoExercicio(caminhoBaseDosExercicios, idDaQuestao);
            abreQuestao(urlDoExercicio);
        } catch (NumberFormatException ex) {
            String mensagemDaExcecao = "Não foi possível obter o número da questão (" + ex.getMessage() + ")";
            PortugolStudio.getInstancia().getTratadorExcecoes().exibirExcecao(new Exception(mensagemDaExcecao, ex));
        } catch (Exception e) {
            PortugolStudio.getInstancia().getTratadorExcecoes().exibirExcecao(e);
        }
    }

    private int getIdDaQuestao() {
        String idDaQuestao = getParameter("idDaQuestao");
        if (idDaQuestao != null) {
            return Integer.parseInt(idDaQuestao);
        }
        return 1;
    }

    private int getIdDoAluno() {
        String idDoaluno = getParameter("idDoAluno");
        if (idDoaluno != null) {
            return Integer.parseInt(idDoaluno);
        }
        return 0;
    }

    @Override
    public void init() {

        initComponents();

        abaCodigoFonte = new AbaCodigoFonteDoApplet(getIdDoAluno(), getIdDaQuestao());

        PortugolStudio portugol = PortugolStudio.getInstancia();
        portugol.iniciar();
        setLayout(new BorderLayout());
        add(abaCodigoFonte, BorderLayout.CENTER);
        //if (recebeuOsParametros()) {
        carregaExercicio();
        //}
    }

    private void instalaLookAndFeel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
