package br.univali.ps;

import br.univali.ps.exception.CarregamentoDeExercicioException;
import br.univali.ps.nucleo.PortugolStudio;
import br.univali.ps.ui.abas.AbaCodigoFonte;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import java.net.MalformedURLException;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.border.Border;


/**
 *
 * @author Elieser
 */
public class TelaPrincipalApplet extends javax.swing.JApplet
{
    private static final long serialVersionUID = 1L;
    private final AbaCodigoFonte abaCodigoFonte;

    public TelaPrincipalApplet() throws HeadlessException
    {
        instalaLookAndFeel();
        abaCodigoFonte = AbaCodigoFonte.criaNovaAba();
    }

    
    
    private void criaAbaParaRealizacaoDeExercicio(String urlDoXmlDoExercicio) throws MalformedURLException, IOException
    {
        try
        {
            PortugolStudio.getInstancia().abrirQuestao(urlDoXmlDoExercicio);
            
        }
        catch (CarregamentoDeExercicioException ex)
        {
            ex.printStackTrace();
            PortugolStudio.getInstancia().getTratadorExcecoes().exibirExcecao(ex);
        }
    }

    private boolean idDoExercicioFoiPassadoComoParametro()
    {
        String idDaQuestao = getParameter("idDaQuestao");
        return idDaQuestao != null && !idDaQuestao.isEmpty();
    }

    private void carregaExercicio()
    {
        String idDaQuestao = getParameter("idDaQuestao");
        AppletUtils.exibeMensagemNaConsoleJava("O applet recebeu o id da questão " + idDaQuestao);
        try
        {
            int id = Integer.parseInt(idDaQuestao);
            //String caminhoBaseDosExercicios = "http://localhost:8080/Alice/exercicios";
            String caminhoBaseDosExercicios = getCodeBase() + getParameter("pathDosExercicios");
            if (caminhoBaseDosExercicios == null)
            {
                throw new IllegalArgumentException("O caminho base dos exercícios não foi passado como parâmetro para o applet!");
            }
            String urlDoExercicio = AppletUtils.getCaminhoDoArquivoDoExercicio(caminhoBaseDosExercicios, id);
            criaAbaParaRealizacaoDeExercicio(urlDoExercicio);
        }
        catch (NumberFormatException ex)
        {
            String mensagemDaExcecao = "Não foi possível obter o número da questão (" + ex.getMessage() + ")";
            PortugolStudio.getInstancia().getTratadorExcecoes().exibirExcecao(new Exception(mensagemDaExcecao, ex));
        }
        catch (Exception e)
        {
            PortugolStudio.getInstancia().getTratadorExcecoes().exibirExcecao(e);
        }
    }

    @Override
    public void init()
    {
        
        initComponents();
        PortugolStudio portugol = PortugolStudio.getInstancia();
        portugol.iniciar();
        setLayout(new BorderLayout());
        add(abaCodigoFonte, BorderLayout.CENTER);
        Border lineBorder = BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1, true);
        Border emptyBorder = BorderFactory.createEmptyBorder(5, 5, 5, 5);
        
        abaCodigoFonte.setBorder(BorderFactory.createCompoundBorder(emptyBorder, lineBorder));
        if (idDoExercicioFoiPassadoComoParametro())
        {
            carregaExercicio();
        }
    }

    private void instalaLookAndFeel(){
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables



}
