/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.window;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.telas.TelaPrincipal;
import java.awt.BorderLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;

/**
 *
 * @author lite
 */
public class OutsidePanel extends javax.swing.JPanel
{

    /**
     * Creates new form OutsidePanelFinal
     */
    public OutsidePanel()
    {
        initComponents();
        setBorder(new LineBorder(ColorController.FUNDO_ESCURO, 5));
        addComponentListener(new ComponentAdapter(){
            @Override
            public void componentResized(ComponentEvent e)
            {
                super.componentResized(e); //To change body of generated methods, choose Tools | Templates.
                SwingUtilities.invokeLater(() ->
                {
                    OutsidePanel.this.repaint();
                });
            }
            
        });
    }
    
    public TelaPrincipal getTelaPrincipal(){
        return this.telaPrincipal1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        borderPanel1 = new br.univali.ps.ui.window.BorderPanel();
        telaPrincipal1 = new br.univali.ps.ui.telas.TelaPrincipal();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        add(borderPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(telaPrincipal1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.univali.ps.ui.window.BorderPanel borderPanel1;
    private br.univali.ps.ui.telas.TelaPrincipal telaPrincipal1;
    // End of variables declaration//GEN-END:variables
}
