/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbaConsole.java
 *
 * Created on 26/09/2011, 19:44:54
 */
package br.univali.ps.ui;

import br.univali.ps.ui.util.IconFactory;
import javax.swing.JTabbedPane;

/**
 *
 * @author fillipipelz
 */
public class AbaConsole extends Aba{

    /** Creates new form AbaConsole */
    public AbaConsole(JTabbedPane painelTabulado) {
        super(painelTabulado);
        cabecalho.setBotaoFecharVisivel(false);
        cabecalho.setTitulo("Console");
        cabecalho.setIcone(IconFactory.createIcon(IconFactory.SMALL_ICONS_PATH, "application_xp_terminal.png"));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }
    // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
