/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbaInicial.java
 *
 * Created on 28/09/2011, 21:02:53
 */
package br.univali.ps.ui;

import javax.swing.JTabbedPane;

/**
 *
 * @author fillipipelz
 */
public class AbaInicial extends Aba {

    /** Creates new form AbaInicial */
    public AbaInicial(JTabbedPane painelTabulado) {
        super(painelTabulado);
        initComponents();
    }

    @Override
    protected CabecalhoAba criarCabecalho() {
        return new BotoesControleAba(this);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
