/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbaInicial.java
 *
 * Created on 28/09/2011, 21:02:53
 */
package br.univali.ps.ui;

import javax.swing.JTabbedPane;

/**
 *
 * @author fillipipelz
 */
public class AbaInicial extends Aba {

    /** Creates new form AbaInicial */
    public AbaInicial(JTabbedPane painelTabulado) {
        super(painelTabulado);
        initComponents();
    }

    @Override
    protected CabecalhoAba criarCabecalho() {
        return new BotoesControleAba(this);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo1 = new br.univali.ps.ui.imagens.Logo();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);
        add(logo1);
        logo1.setBounds(20, 20, 260, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/pequeno/univali.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(20, 590, 80, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/grande/Light and line_4_Blue_1280 x 1024-1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1280, 1024);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private br.univali.ps.ui.imagens.Logo logo1;
    // End of variables declaration//GEN-END:variables
}
