/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

import br.univali.ps.nucleo.Configuracoes;
import br.univali.ps.nucleo.PortugolStudio;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.utils.FabricaDicasInterface;
import br.univali.ps.ui.utils.IconFactory;
import br.univali.ps.ui.utils.WebConnectionUtils;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author lite
 */
public class Sobre extends javax.swing.JPanel implements Themeable
{
    
    /**
     * Creates new form Sobre
     */
    public Sobre()
    {
        initComponents();
        
        setSize(750, 550);
//        rotuloDescricao.setText(String.format(rotuloDescricao.getText(), PortugolStudio.getInstancia().getVersao()));

        configurarLinks();
        FabricaDicasInterface.criarTooltip(labellicensa, "Veja as Licensas do Software");
        labellicensa.setIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_GRANDES, "license.png"));
        configurarCores();
        versaoLabel.setText("v"+PortugolStudio.getInstancia().getVersao());
    }
    
    @Override
    public void configurarCores(){
        painelConteudo.setBackground(ColorController.FUNDO_CLARO);
        paineInferior.setBackground(ColorController.FUNDO_ESCURO);
        versaoLabel.setForeground(ColorController.COR_LETRA);
        jPanel1.setBackground(ColorController.FUNDO_ESCURO);
        jLabel1.setBackground(ColorController.COR_PRINCIPAL);
        jLabel1.setText(carregarHTML("/br/univali/ps/ui/telas/"+Configuracoes.getInstancia().getTemaPortugol()+"/membros.html"));
    }
    
    private void configurarLinks()
    {
        configurarLink(jLabel2);
        configurarLink(rotuloBitRock);
        configurarLink(rotuloGithub);
        configurarLink(rotuloOsi);
        configurarLink(rotuloUnivali);
    }

    private void configurarLink(final JLabel rotulo)
    {
        rotulo.addMouseListener(new MouseAdapter()
        {

            @Override
            public void mouseClicked(MouseEvent e)
            {
                WebConnectionUtils.abrirSite(rotulo.getName());
            }
        });
    }
    
    private String carregarHTML(String caminho)
    {
        StringBuilder contentBuilder = new StringBuilder();
        try {
            BufferedReader in = new BufferedReader(new InputStreamReader(getClass().getResourceAsStream(caminho), Charset.forName("UTF-8")));
            String str;
            while ((str = in.readLine()) != null) {
                contentBuilder.append(str);
            }
            in.close();
        } catch (IOException e) {
            System.out.println(e);
        }
        String base = contentBuilder.toString();
        
        return base;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        painelConteudo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logo1 = new br.univali.ps.ui.imagens.Logo();
        jLabel2 = new javax.swing.JLabel();
        versaoLabel = new javax.swing.JLabel();
        paineInferior = new javax.swing.JPanel();
        rotuloGithub = new javax.swing.JLabel();
        rotuloOsi = new javax.swing.JLabel();
        rotuloUnivali = new javax.swing.JLabel();
        rotuloBitRock = new javax.swing.JLabel();
        labellicensa = new javax.swing.JLabel();

        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        mainpanel.setLayout(new java.awt.BorderLayout());

        painelConteudo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        painelConteudo.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("<html>   <head>     <style>       body{         background-color: rgb(38,50,56);         color: rgb(205,205,205);       }       .ativo b{         color: rgb(0,239,192);       }       .inativo b{         color: rgb(255,194,0);       }       h1{         color: rgb(69,189,255);       }     </style>   </head>   <body>     <h1> Membros Ativos </h1>     <div class=\"ativo\">       <b>Adson Marques Da Silva Esteves :</b> Atua no projeto como programador e designer     </div>     <div class=\"ativo\">       <b>Alisson Steffens Henrique :</b> Atua no projeto como programador e designer     </div>     <div class=\"ativo\">       <b>André Luis Alice Raabe :</b> Atua no projeto como coordenador     </div>     <div class=\"ativo\">       <b>André Luiz Maciel Santana :</b> Atua no projeto como orientador     </div>     <div class=\"ativo\">       <b>Elieser A. de Jesus :</b> Atua no projeto como programador e designer     </div>     <div class=\"ativo\">       <b>Luiz Fernando Noschang :</b> Atua no projeto como programador e designer     </div>     <div class=\"ativo\">       <b>Paulo Eduardo Martins :</b> Atua no projeto como programador e editor de conteúdo     </div>     <h1> Membros Inativos </h1>     <div class=\"inativo\">       <b>Carlos Alexangre Krueger :</b> Atuou no projeto como editor de conteúdo     </div>     <div class=\"inativo\">       <b>Fillipi Pelz :</b> Atuou no projeto como programador     </div>     <div class=\"inativo\">       <b>Giordana M. da C. Valle :</b> Atuou no projeto como editora de conteúdo     </div>     <div class=\"inativo\">       <b>Nereu Oliveira :</b> Atuou no projeto como programador     </div>     <div class=\"inativo\">       <b>Paula Mannes :</b> Atuou no projeto como programadora     </div>     <div class=\"inativo\">       <b>Roberto Gonçalves Augusto Júnior :</b> Atuou no projeto como editor de conteúdo     </div>     </body> </html> ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        painelConteudo.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        logo1.setMaximumSize(new java.awt.Dimension(310, 100));
        logo1.setMinimumSize(new java.awt.Dimension(310, 100));
        logo1.setOpaque(false);
        jPanel1.add(logo1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/logo_lite.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setName("http://lite.acad.univali.br/pt/"); // NOI18N
        jPanel1.add(jLabel2);

        painelConteudo.add(jPanel1, java.awt.BorderLayout.WEST);

        versaoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        versaoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versaoLabel.setText("jLabel3");
        painelConteudo.add(versaoLabel, java.awt.BorderLayout.PAGE_END);

        mainpanel.add(painelConteudo, java.awt.BorderLayout.CENTER);

        add(mainpanel, java.awt.BorderLayout.CENTER);

        paineInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        paineInferior.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        rotuloGithub.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rotuloGithub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloGithub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/logo_github.png"))); // NOI18N
        rotuloGithub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloGithub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rotuloGithub.setName("https://github.com/"); // NOI18N
        paineInferior.add(rotuloGithub);

        rotuloOsi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rotuloOsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloOsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/logo_osi.png"))); // NOI18N
        rotuloOsi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloOsi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rotuloOsi.setName("http://opensource.org/"); // NOI18N
        paineInferior.add(rotuloOsi);

        rotuloUnivali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rotuloUnivali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloUnivali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/logo_univali.png"))); // NOI18N
        rotuloUnivali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloUnivali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rotuloUnivali.setMaximumSize(new java.awt.Dimension(48, 40));
        rotuloUnivali.setMinimumSize(new java.awt.Dimension(48, 40));
        rotuloUnivali.setName("https://www.univali.br/graduacao/ciencia-da-computacao-itajai/Paginas/default.aspx"); // NOI18N
        paineInferior.add(rotuloUnivali);

        rotuloBitRock.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rotuloBitRock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloBitRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/imagens/logo_bitrock.png"))); // NOI18N
        rotuloBitRock.setToolTipText("");
        rotuloBitRock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloBitRock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rotuloBitRock.setName("http://installbuilder.bitrock.com/"); // NOI18N
        paineInferior.add(rotuloBitRock);

        labellicensa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellicensa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/grande/license.png"))); // NOI18N
        labellicensa.setToolTipText("");
        labellicensa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labellicensa.setMaximumSize(new java.awt.Dimension(48, 40));
        labellicensa.setMinimumSize(new java.awt.Dimension(48, 40));
        labellicensa.setPreferredSize(null);
        labellicensa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labellicensaMouseClicked(evt);
            }
        });
        paineInferior.add(labellicensa);

        add(paineInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void labellicensaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labellicensaMouseClicked
    {//GEN-HEADEREND:event_labellicensaMouseClicked
        JDialog telaLicencas = PortugolStudio.getInstancia().getTelaLicencas();
        telaLicencas.setVisible(true);
    }//GEN-LAST:event_labellicensaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labellicensa;
    private br.univali.ps.ui.imagens.Logo logo1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel paineInferior;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JLabel rotuloBitRock;
    private javax.swing.JLabel rotuloGithub;
    private javax.swing.JLabel rotuloOsi;
    private javax.swing.JLabel rotuloUnivali;
    private javax.swing.JLabel versaoLabel;
    // End of variables declaration//GEN-END:variables
}
