package br.univali.ps.ui.telas;

import br.univali.ps.nucleo.Configuracoes;
import br.univali.ps.nucleo.PortugolStudio;
import br.univali.ps.ui.paineis.PainelTextoAlerta;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.PSMainTabbedPaneUI;
import br.univali.ps.ui.utils.FileHandle;
import br.univali.ps.ui.utils.WebConnectionUtils;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Adson Estevesa
 */
public class TelaAlertas extends javax.swing.JPanel implements Themeable {

    PainelTextoAlerta painelAlerta;
       
    public TelaAlertas(PainelTextoAlerta painelAlerta) {
        this.painelAlerta = painelAlerta;
        initComponents();
        configurarCores();      
        loadAlerta();
    }

    @Override
    public void configurarCores() {
        this.labelSemAlertas.setForeground(ColorController.COR_LETRA);
        this.labelTitulo.setForeground(ColorController.COR_LETRA);
        this.painelAlertas.setForeground(ColorController.COR_LETRA);
        this.caixaCheckLido.setForeground(ColorController.COR_LETRA);
        setBackground(ColorController.COR_DESTAQUE);
        this.painelDeBaixo.setOpaque(false);
        this.painelTitulo.setBackground(ColorController.VERMELHO);
        this.painelAlertas.setOpaque(false);
    }

    private void loadAlerta() {
        
        try {
            painelAlertas.removeAll();
            painelAlertas.add(this.painelAlerta);            
            revalidate();
            repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        painelDeBaixo = new javax.swing.JPanel();
        caixaCheckLido = new javax.swing.JCheckBox();
        painelAlertas = new javax.swing.JPanel();
        labelSemAlertas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 550));
        setLayout(new java.awt.BorderLayout());

        painelTitulo.setMaximumSize(new java.awt.Dimension(640, 100));
        painelTitulo.setMinimumSize(new java.awt.Dimension(640, 100));
        painelTitulo.setPreferredSize(new java.awt.Dimension(640, 100));
        painelTitulo.setLayout(new java.awt.BorderLayout());

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Alerta Importante!");
        painelTitulo.add(labelTitulo, java.awt.BorderLayout.CENTER);

        add(painelTitulo, java.awt.BorderLayout.NORTH);

        painelDeBaixo.setMaximumSize(new java.awt.Dimension(640, 40));
        painelDeBaixo.setMinimumSize(new java.awt.Dimension(640, 40));
        painelDeBaixo.setPreferredSize(new java.awt.Dimension(640, 40));
        painelDeBaixo.setLayout(new java.awt.BorderLayout());

        caixaCheckLido.setText("Li os avisos e não quero que apareçam novamente");
        caixaCheckLido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaCheckLidoActionPerformed(evt);
            }
        });
        painelDeBaixo.add(caixaCheckLido, java.awt.BorderLayout.CENTER);

        add(painelDeBaixo, java.awt.BorderLayout.SOUTH);

        labelSemAlertas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelSemAlertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSemAlertas.setText("Não há Alertas ou Avisos!");
        painelAlertas.add(labelSemAlertas);

        add(painelAlertas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void caixaCheckLidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaCheckLidoActionPerformed
        PortugolStudio.getInstancia().adicionaMensagemLida(this.painelAlerta.getIdMensagem());
    }//GEN-LAST:event_caixaCheckLidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox caixaCheckLido;
    private javax.swing.JLabel labelSemAlertas;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelAlertas;
    private javax.swing.JPanel painelDeBaixo;
    private javax.swing.JPanel painelTitulo;
    // End of variables declaration//GEN-END:variables
}
