/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import com.alee.laf.button.WebButton;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import org.json.JSONObject;

/**
 *
 * @author Adson Esteves
 */
public class TelaEditarTemas extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form TelaEditarTemas
     */
    
    TelaCustomBorder dialog;
    
    public TelaEditarTemas(TelaCustomBorder dialog) {
        initComponents();
        this.dialog = dialog;
        configurarCores();
        carregarTemas();
    }
    
    private void carregarTemas()
    {
        String[] temas = ColorController.listarTemas();
        
        for (String tema : temas) 
        {
            comboBoxTemas.addItem(tema);
        }
        carregarCoresTema(temas[0]);
    }
    
    private void carregarCoresTema(String tema)
    {
        JSONObject temas = ColorController.getTemas();
        JSONObject coresTema = temas.getJSONObject(tema);
        
        for (String name : JSONObject.getNames(coresTema)) 
        {
            if(!name.equals("Editor"))
            {
                JPanel estilo = new JPanel();
                estilo.setOpaque(true);
                estilo.setBorder(new LineBorder(Color.BLACK, 2));
                estilo.setAlignmentY(LEFT_ALIGNMENT);
                JLabel nomeVariavel = new JLabel(name);
                nomeVariavel.setPreferredSize(new Dimension(10, 5));
                nomeVariavel.setForeground(ColorController.COR_LETRA);
                WebButton botaoColorPicker = new WebButton("+");
                WeblafUtils.configurarBotao(botaoColorPicker);
                estilo.add(nomeVariavel);
                estilo.add(botaoColorPicker);
                estilo.revalidate();
                painelVariaveisPSInterior.add(estilo);
                
            }
        }
        painelVariaveisPSInterior.setSize(new Dimension(100, 60));
        JSONObject coresEditor = coresTema.getJSONObject("Editor");
        
        for (String name : JSONObject.getNames(coresEditor)) 
        {
            JPanel estilo = new JPanel();
            estilo.setOpaque(true);
            estilo.setBorder(new LineBorder(Color.BLACK, 2));
            estilo.setAlignmentY(LEFT_ALIGNMENT);
            JLabel nomeVariavel = new JLabel(name);
            nomeVariavel.setForeground(ColorController.COR_LETRA);
            WebButton botaoColorPicker = new WebButton("+");
            WeblafUtils.configurarBotao(botaoColorPicker);
            estilo.add(nomeVariavel);
            estilo.add(botaoColorPicker);
            estilo.revalidate();
            painelVariaveisEditorInterior.add(estilo);
        }
    }

    @Override
    public void configurarCores() {
        setBackground(ColorController.FUNDO_MEDIO);
        setForeground(ColorController.COR_LETRA);
        labelTemas.setForeground(ColorController.COR_LETRA);
        labelEditor.setForeground(ColorController.COR_LETRA);
        labelPS.setForeground(ColorController.COR_LETRA);
        if(WeblafUtils.weblafEstaInstalado())
        {
            WeblafUtils.configuraWebLaf(comboBoxTemas);
            WeblafUtils.configuraWebLaf(variavelScrollPane);
            WeblafUtils.configurarBotao(botaoNovoTema, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA_TITULO, ColorController.FUNDO_CLARO, ColorController.COR_LETRA, 5, true);
            WeblafUtils.configurarBotao(botaoAplicarTema, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA_TITULO, ColorController.FUNDO_CLARO, ColorController.COR_LETRA, 5, true);
            WeblafUtils.configurarBotao(botaoCancelar, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA_TITULO, ColorController.FUNDO_CLARO, ColorController.COR_LETRA, 5, true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        variavelScrollPane = new javax.swing.JScrollPane();
        painelVariaveis = new javax.swing.JPanel();
        painelVariaveisEditor = new javax.swing.JPanel();
        labelEditor = new javax.swing.JLabel();
        painelVariaveisEditorInterior = new javax.swing.JPanel();
        painelVariaveisIDE = new javax.swing.JPanel();
        labelPS = new javax.swing.JLabel();
        painelVariaveisPSInterior = new javax.swing.JPanel();
        labelTemas = new javax.swing.JLabel();
        botaoNovoTema = new com.alee.laf.button.WebButton();
        comboBoxTemas = new com.alee.laf.combobox.WebComboBox();
        botaoAplicarTema = new com.alee.laf.button.WebButton();
        botaoCancelar = new com.alee.laf.button.WebButton();

        variavelScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        variavelScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        variavelScrollPane.setOpaque(false);

        painelVariaveis.setOpaque(false);
        painelVariaveis.setLayout(new java.awt.BorderLayout());

        painelVariaveisEditor.setOpaque(false);
        painelVariaveisEditor.setLayout(new java.awt.BorderLayout());

        labelEditor.setText("Editor");
        painelVariaveisEditor.add(labelEditor, java.awt.BorderLayout.PAGE_START);

        painelVariaveisEditorInterior.setOpaque(false);
        painelVariaveisEditorInterior.setLayout(new java.awt.GridLayout(5, 3));
        painelVariaveisEditor.add(painelVariaveisEditorInterior, java.awt.BorderLayout.CENTER);

        painelVariaveis.add(painelVariaveisEditor, java.awt.BorderLayout.CENTER);

        painelVariaveisIDE.setOpaque(false);
        painelVariaveisIDE.setLayout(new java.awt.BorderLayout());

        labelPS.setText("Portugol Studio");
        painelVariaveisIDE.add(labelPS, java.awt.BorderLayout.PAGE_START);

        painelVariaveisPSInterior.setOpaque(false);
        painelVariaveisPSInterior.setLayout(new java.awt.GridLayout(5, 3));
        painelVariaveisIDE.add(painelVariaveisPSInterior, java.awt.BorderLayout.CENTER);

        painelVariaveis.add(painelVariaveisIDE, java.awt.BorderLayout.NORTH);

        variavelScrollPane.setViewportView(painelVariaveis);

        labelTemas.setText("Temas");

        botaoNovoTema.setText("+");
        botaoNovoTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoTemaActionPerformed(evt);
            }
        });

        botaoAplicarTema.setText("aplicar tema");

        botaoCancelar.setText("cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(variavelScrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(botaoAplicarTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(labelTemas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoNovoTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTemas)
                        .addComponent(botaoNovoTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(variavelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAplicarTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoNovoTemaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAplicarTema;
    private com.alee.laf.button.WebButton botaoCancelar;
    private com.alee.laf.button.WebButton botaoNovoTema;
    private com.alee.laf.combobox.WebComboBox comboBoxTemas;
    private javax.swing.JLabel labelEditor;
    private javax.swing.JLabel labelPS;
    private javax.swing.JLabel labelTemas;
    private javax.swing.JPanel painelVariaveis;
    private javax.swing.JPanel painelVariaveisEditor;
    private javax.swing.JPanel painelVariaveisEditorInterior;
    private javax.swing.JPanel painelVariaveisIDE;
    private javax.swing.JPanel painelVariaveisPSInterior;
    private javax.swing.JScrollPane variavelScrollPane;
    // End of variables declaration//GEN-END:variables
}
