/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.telas;

import br.univali.portugol.nucleo.bibliotecas.base.GerenciadorBibliotecas;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author 5663296
 */
public class TelaNovoProjeto extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form TelaNovoProjeto
     */
    public TelaNovoProjeto() {
        initComponents();
        List<String> libs = GerenciadorBibliotecas.getInstance().getBibliotecasDisponiveis();
        for (String lib : libs) {
            JCheckBox check = new JCheckBox(lib);
            check.setForeground(ColorController.COR_LETRA);
            painelCheckBox.add(check);
        }
        configurarCores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pergunta = new javax.swing.JLabel();
        painelCheckBox = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        pergunta.setText("Quais Bibliotecas serão utilizadas?");
        pergunta.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel1.add(pergunta, java.awt.BorderLayout.PAGE_START);

        painelCheckBox.setLayout(new java.awt.GridLayout(0, 3));
        jPanel1.add(painelCheckBox, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Este é um programa:");
        jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jToggleButton1.setText("jToggleButton1");
        jPanel3.add(jToggleButton1);

        jToggleButton2.setText("jToggleButton2");
        jPanel3.add(jToggleButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel painelCheckBox;
    private javax.swing.JLabel pergunta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarCores() {
        this.setBackground(ColorController.COR_PRINCIPAL);
        jLabel1.setForeground(ColorController.AMARELO);
        pergunta.setForeground(ColorController.COR_LETRA);
        painelCheckBox.setBackground(ColorController.COR_CONSOLE);
        
//        WeblafUtils.configurarBotao(botaoConsole, ColorController.AMARELO, ColorController.COR_LETRA, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, 10);
//        WeblafUtils.configurarBotao(botaoGrafico, ColorController.AMARELO, ColorController.COR_LETRA, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, 10);
    }
}
