/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.ajuda;

import javax.swing.JButton;

/**
 *
 * @author Carlos
 */
public class BotoesHelp extends javax.swing.JPanel
{
    private FuncoesHelp funcionalidades;
    /**
     * Creates new form BotoesHelp
     */
    public BotoesHelp()
    {
        initComponents();
    }

    public BotoesHelp(FuncoesHelp funcionalidades)
    {
        this.funcionalidades = funcionalidades;
    }
    

    public void setFuncionalidades(FuncoesHelp funcionalidades)
    {
        this.funcionalidades = funcionalidades;
    }
    
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)                                         
    {                                             
        funcionalidades.aumentarFonte(); 
    }  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)                                         
    {                                             
         funcionalidades.aumentarFonte(); 
    }  
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)                                         
    {                                             
         funcionalidades.imprimeAba(); 
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/pequeno/font_add.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/pequeno/font_delete.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/pequeno/printer.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2)
            .addComponent(jButton1)
            .addComponent(jButton3)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
