/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.abas.utilitarios;

import br.univali.ps.ui.abas.Aba;
import br.univali.ps.ui.abas.AbaCodigoFonte;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import br.univali.ps.ui.utils.IconFactory;
import com.alee.laf.button.WebButton;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author 5663296
 */
public class AbaGerenciadorTemplates extends Aba implements Themeable{
    private AbaCodigoFonte abaCodigoFonte;

    /**
     * Creates new form AbaGerenciadorTemplates
     */
    public AbaGerenciadorTemplates(AbaCodigoFonte abaCodigoFonte) {
        super("Templates", IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "real.png"), false);
        this.abaCodigoFonte = abaCodigoFonte;
        initComponents();
        String[] templates = {"console", "grafico"};
        for (String template : templates) {
            WebButton temp = new WebButton();
            temp.setText("asd");
            temp.setName(template);
            temp.setForeground(ColorController.COR_LETRA);
            temp.setAction(new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    abaCodigoFonte.setarTemplate(template);
                }
            });
            WeblafUtils.configurarBotao(temp, ColorController.AMARELO, ColorController.COR_LETRA, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, 5);
            add(temp);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 2));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarCores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
