/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.abas.utilitarios;

import br.univali.ps.ui.abas.Aba;
import br.univali.ps.ui.abas.AbaCodigoFonte;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.utils.IconFactory;

/**
 *
 * @author 5663296
 */
public class AbaGerenciadorTemplates extends Aba implements Themeable{
    private AbaCodigoFonte abaCodigoFonte;

    /**
     * Creates new form AbaGerenciadorTemplates
     */
    public AbaGerenciadorTemplates(AbaCodigoFonte abaCodigoFonte) {
        super("Templates", IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "real.png"), false);
        this.abaCodigoFonte = abaCodigoFonte;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webButton1 = new com.alee.laf.button.WebButton();
        webButton2 = new com.alee.laf.button.WebButton();

        setLayout(new java.awt.BorderLayout());

        webButton1.setText("webButton1");
        add(webButton1, java.awt.BorderLayout.CENTER);

        webButton2.setText("webButton2");
        add(webButton2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarCores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
