/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.abas.utilitarios;

import br.univali.ps.nucleo.Configuracoes;
import br.univali.ps.ui.abas.Aba;
import br.univali.ps.ui.abas.AbaCodigoFonte;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import br.univali.ps.ui.utils.FabricaDicasInterface;
import br.univali.ps.ui.utils.IconFactory;
import com.alee.laf.button.WebButton;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author 5663296
 */
public class AbaGerenciadorTemplates extends Aba implements Themeable{
    private AbaCodigoFonte abaCodigoFonte;

    /**
     * Creates new form AbaGerenciadorTemplates
     */
    public AbaGerenciadorTemplates(AbaCodigoFonte abaCodigoFonte) {
        super("Modelos", IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "template.png"), false);
        this.abaCodigoFonte = abaCodigoFonte;
        initComponents();
        configurarCores();
        String[] templates = {"console","grafico", "jogo","arquivos", "internet"};
        for (String template : templates) {
            WebButton temp = new WebButton();
            temp.setText(template);
            temp.setName(template);
            temp.setForeground(ColorController.COR_LETRA);
            temp.setAction(new AbstractAction(template){        
                @Override
                public void actionPerformed(ActionEvent ae) {
                    abaCodigoFonte.setarTemplate(template);
                }
            });
                   
            WeblafUtils.configurarBotao(temp, ColorController.FUNDO_ESCURO, ColorController.COR_PRINCIPAL, ColorController.FUNDO_MEDIO, ColorController.COR_LETRA, 5);            
            if(Configuracoes.getInstancia().isTemaDark())
            {
                WeblafUtils.configurarBotao(temp, ColorController.AMARELO, ColorController.COR_PRINCIPAL, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, 5);                
            }
            add(temp);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.GridLayout(0, 2, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarCores() {
        setBackground(ColorController.FUNDO_BOTOES_EXPANSIVEIS);
    }
}
