/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.abas;

import br.univali.ps.nucleo.Configuracoes;
import br.univali.ps.nucleo.PortugolStudio;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import br.univali.ps.ui.utils.FabricaDicasInterface;
import br.univali.ps.ui.utils.IconFactory;
import java.awt.Dimension;
import javax.swing.border.MatteBorder;

/**
 *
 * @author 5663296
 */
public class CabecalhoAdicionarAba extends javax.swing.JPanel {

    /**
     * Creates new form CabecalhoAdicionarAba
     */
    public CabecalhoAdicionarAba() {
        initComponents();
        setBackground(ColorController.COR_DESTAQUE);
        setPreferredSize(new Dimension(30,30));
        setBorder(new MatteBorder(0, 1, 0, 0, ColorController.FUNDO_ESCURO));
        if (WeblafUtils.weblafEstaInstalado()) {
            WeblafUtils.configurarBotao(botaoAbrir,ColorController.TRANSPARENTE,ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 1);
        }
        botaoAbrir.setIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "plus2.png"));
        //FabricaDicasInterface.criarTooltipEstatica(botaoAbrir, "Adicionar nova aba");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAbrir = new com.alee.laf.button.WebButton();

        setMinimumSize(new java.awt.Dimension(25, 25));
        setPreferredSize(new java.awt.Dimension(26, 26));
        setLayout(new java.awt.BorderLayout());

        botaoAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/plus2.png"))); // NOI18N
        botaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirActionPerformed(evt);
            }
        });
        add(botaoAbrir, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirActionPerformed
        PortugolStudio.getInstancia().getTelaPrincipal().criarNovoCodigoFonte();
    }//GEN-LAST:event_botaoAbrirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAbrir;
    // End of variables declaration//GEN-END:variables
}
