/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.paineis;

import br.univali.portugol.nucleo.bibliotecas.base.GerenciadorBibliotecas;
import br.univali.ps.ui.abas.AbaCodigoFonte;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import br.univali.ps.ui.utils.IconFactory;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author 5663296
 */
public class PainelGerenciadorBibliotecas extends javax.swing.JPanel implements Themeable{
    
    private AbaCodigoFonte abaCodigoFonte;
    /**
     * Creates new form PainelTemplates
     */
    public void updateBibliotecas(){
        for (Component component : painelCheckBox.getComponents()) {
            JCheckBox check = (JCheckBox) component;
            if(abaCodigoFonte.getPortugolDocumento().getCodigoFonte().contains("inclua biblioteca "+check.getText())){
                check.setSelected(true);
            }
        }
    }
    public void reseta(){
        for (Component component : painelCheckBox.getComponents()) {
            JCheckBox check = (JCheckBox) component;
            check.setSelected(false);
            
        }
    }
    
    public PainelGerenciadorBibliotecas(AbaCodigoFonte abaCodigoFonte) {
        this.abaCodigoFonte = abaCodigoFonte;
        initComponents();
        closebutton.setText("");
        closebutton.setIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "window_close.png"));
        List<String> libs = GerenciadorBibliotecas.getInstance().getBibliotecasDisponiveis();
        for (String lib : libs) {
            JCheckBox check = new JCheckBox(lib);
            check.setForeground(ColorController.COR_LETRA);
            check.setSelectedIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "selected.png"));
            check.setIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "unselected.png"));
            if(abaCodigoFonte.getPortugolDocumento().getCodigoFonte().contains("inclua biblioteca "+lib)){
                check.setSelected(true);
            }
            
            check.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent ie) {
                    if(ie.getStateChange() == ItemEvent.SELECTED){
                        abaCodigoFonte.adicionarBiblioteca(((JCheckBox)ie.getItem()).getText());
                    }else{
                        abaCodigoFonte.removerBiblioteca(((JCheckBox)ie.getItem()).getText());
                    }
                }
            });
            painelCheckBox.add(check);
        }
        configurarCores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        painelCheckBox = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closebutton = new com.alee.laf.button.WebButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        painelCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        painelCheckBox.setLayout(new java.awt.GridLayout(0, 3));
        jPanel1.add(painelCheckBox, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gerenciar Bibliotecas");
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        closebutton.setText("x");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        jPanel4.add(closebutton, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton closebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel painelCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarCores() {
        this.setBackground(ColorController.COR_PRINCIPAL);
        jLabel1.setForeground(ColorController.AMARELO);
        painelCheckBox.setBackground(ColorController.FUNDO_BOTOES_EXPANSIVEIS);
        WeblafUtils.configurarBotao(closebutton, ColorController.COR_PRINCIPAL, Color.white, ColorController.FUNDO_CLARO, Color.orange, 1);
        //WeblafUtils.configurarBotao(botaoAdicionar, ColorController.AMARELO, ColorController.COR_PRINCIPAL, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA,2);
    }
}
