/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.paineis;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import br.univali.ps.ui.utils.WebConnectionUtils;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import org.fife.ui.rsyntaxtextarea.Style;

/**
 *
 * @author Space Today
 */
public class PainelTextoAlerta extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form PainelTextoAlerta
     */
    String idMensagem = "";
    
    public PainelTextoAlerta(String titulo, String subtitulo, String mensagem, String link, String idmensagem) {
        initComponents();
        configurarCores();
        
        this.idMensagem = idmensagem;
        this.labelTituloMensagem.setText(titulo);
        this.labelSubTituloMensagem.setText(subtitulo);
        
        appendToPane(painelTextoMensagem, mensagem, ColorController.COR_LETRA);
        
        if(!link.equals(""))
        {
            this.botaoLinkMensagem.setAction(new AbstractAction("Acessar Link") {
                @Override
                public void actionPerformed(ActionEvent e) {
                    WebConnectionUtils.abrirSite(link);
                }
            });
        }
        else
        {
            this.botaoLinkMensagem.setVisible(false);
        }
        
        
        this.painelTextoMensagem.setEditable(false);
    }

    @Override
    public void configurarCores() {
        if (WeblafUtils.weblafEstaInstalado()) {
            WeblafUtils.configuraWebLaf(painelScrollMensagem);
            WeblafUtils.configuraWebLaf(painelTextoMensagem);
            WeblafUtils.configurarBotao(botaoLinkMensagem, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA_TITULO, ColorController.AMARELO, ColorController.COR_PRINCIPAL, 3, true);
        }
        
        painelBotoes.setOpaque(false);
        labelTituloMensagem.setOpaque(false);
        labelSubTituloMensagem.setOpaque(false);
        
        setBackground(ColorController.COR_DESTAQUE);
        labelTituloMensagem.setForeground(ColorController.COR_LETRA);
        labelSubTituloMensagem.setForeground(ColorController.COR_LETRA);
        
    }
    
    private void appendToPane(JTextPane tp, String msg, Color c)
    {
        StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, c);

        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Arial");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);

        int len = tp.getDocument().getLength();
        tp.setCaretPosition(len);
        tp.setCharacterAttributes(aset, false);
        tp.replaceSelection(msg);
    }

    public String getIdMensagem() {
        return idMensagem;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelTituloMensagem = new javax.swing.JLabel();
        labelSubTituloMensagem = new javax.swing.JLabel();
        painelScrollMensagem = new javax.swing.JScrollPane();
        painelTextoMensagem = new javax.swing.JTextPane();
        painelBotoes = new javax.swing.JPanel();
        botaoLinkMensagem = new com.alee.laf.button.WebButton();

        setMaximumSize(new java.awt.Dimension(640, 380));
        setMinimumSize(new java.awt.Dimension(640, 380));
        setLayout(new java.awt.GridBagLayout());

        labelTituloMensagem.setFont(new java.awt.Font("Arial", 1, 42)); // NOI18N
        labelTituloMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloMensagem.setText("Título");
        labelTituloMensagem.setAlignmentY(0.0F);
        labelTituloMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTituloMensagem.setMaximumSize(new java.awt.Dimension(640, 50));
        labelTituloMensagem.setMinimumSize(new java.awt.Dimension(640, 50));
        labelTituloMensagem.setPreferredSize(new java.awt.Dimension(640, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(labelTituloMensagem, gridBagConstraints);

        labelSubTituloMensagem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelSubTituloMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubTituloMensagem.setText("Subtítulo");
        labelSubTituloMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelSubTituloMensagem.setMaximumSize(new java.awt.Dimension(640, 20));
        labelSubTituloMensagem.setMinimumSize(new java.awt.Dimension(640, 20));
        labelSubTituloMensagem.setPreferredSize(new java.awt.Dimension(640, 20));
        labelSubTituloMensagem.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(labelSubTituloMensagem, gridBagConstraints);

        painelScrollMensagem.setMaximumSize(new java.awt.Dimension(640, 260));
        painelScrollMensagem.setMinimumSize(new java.awt.Dimension(640, 260));
        painelScrollMensagem.setPreferredSize(new java.awt.Dimension(640, 260));
        painelScrollMensagem.setRequestFocusEnabled(false);

        painelTextoMensagem.setMinimumSize(new java.awt.Dimension(640, 260));
        painelTextoMensagem.setPreferredSize(new java.awt.Dimension(640, 260));
        painelScrollMensagem.setViewportView(painelTextoMensagem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(painelScrollMensagem, gridBagConstraints);

        painelBotoes.setMaximumSize(new java.awt.Dimension(640, 50));
        painelBotoes.setMinimumSize(new java.awt.Dimension(640, 50));
        painelBotoes.setName(""); // NOI18N
        painelBotoes.setPreferredSize(new java.awt.Dimension(640, 50));

        botaoLinkMensagem.setText("Acessar Link");
        botaoLinkMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painelBotoes.add(botaoLinkMensagem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(painelBotoes, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoLinkMensagem;
    private javax.swing.JLabel labelSubTituloMensagem;
    private javax.swing.JLabel labelTituloMensagem;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JScrollPane painelScrollMensagem;
    private javax.swing.JTextPane painelTextoMensagem;
    // End of variables declaration//GEN-END:variables
}
