/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.paineis;

import br.univali.portugol.nucleo.bibliotecas.base.GerenciadorBibliotecas;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import br.univali.ps.ui.utils.IconFactory;
import java.awt.Color;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author 5663296
 */
public class PainelTemplates extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form PainelTemplates
     */
    public PainelTemplates() {
        initComponents();
        closebutton.setText("");
        closebutton.setIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "window_close.png"));
        List<String> libs = GerenciadorBibliotecas.getInstance().getBibliotecasDisponiveis();
        for (String lib : libs) {
            JCheckBox check = new JCheckBox(lib);
            check.setForeground(ColorController.COR_LETRA);
            check.setSelectedIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "selected.png"));
            check.setIcon(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "unselected.png"));
            painelCheckBox.add(check);
        }
        configurarCores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pergunta = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botaoAdicionar = new com.alee.laf.button.WebButton();
        painelCheckBox = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closebutton = new com.alee.laf.button.WebButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        pergunta.setText("Quais Bibliotecas serão utilizadas?");
        pergunta.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel1.add(pergunta, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        botaoAdicionar.setText("Adicionar");
        jPanel5.add(botaoAdicionar, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        painelCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        painelCheckBox.setLayout(new java.awt.GridLayout(0, 3));
        jPanel1.add(painelCheckBox, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jToggleButton1.setText("jToggleButton1");
        jPanel3.add(jToggleButton1);

        jToggleButton2.setText("jToggleButton2");
        jPanel3.add(jToggleButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Este é um programa:");
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        closebutton.setText("x");
        jPanel4.add(closebutton, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAdicionar;
    private com.alee.laf.button.WebButton closebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel painelCheckBox;
    private javax.swing.JLabel pergunta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarCores() {
        this.setBackground(ColorController.COR_PRINCIPAL);
        jLabel1.setForeground(ColorController.AMARELO);
        pergunta.setForeground(ColorController.COR_LETRA);
        painelCheckBox.setBackground(ColorController.FUNDO_BOTOES_EXPANSIVEIS);
        WeblafUtils.configurarBotao(closebutton, ColorController.COR_PRINCIPAL, Color.white, ColorController.FUNDO_CLARO, Color.orange, 1);
        WeblafUtils.configurarBotao(botaoAdicionar, ColorController.AMARELO, ColorController.COR_PRINCIPAL, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA,2);
    }
}
