/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.ui.editor;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import com.alee.laf.button.WebButton;

/**
 *
 * @author Adson Esteves
 */
public class MiniBarraDeFerramentas extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form MiniBarraDeFerramentas
     */
    public MiniBarraDeFerramentas() {
        initComponents();
        configurarCores();
    }

    @Override
    public void configurarCores() {
        if (WeblafUtils.weblafEstaInstalado()) {
            WeblafUtils.configurarBotao(botaoPlay, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
            WeblafUtils.configurarBotao(botaoAjuda, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
            WeblafUtils.configurarBotao(botaoParar, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
            WeblafUtils.configurarBotao(botaoPasso, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
            WeblafUtils.configurarBotao(botaoSalvar, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
            WeblafUtils.configurarBotao(botaoSalvarComo, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
            WeblafUtils.configurarBotao(botaoAbrir, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 5);
        }
    }
    
    public WebButton getBotaoAbrir() {
        return botaoAbrir;
    }

    public void setBotaoAbrir(WebButton botaoAbrir) {
        this.botaoAbrir = botaoAbrir;
    }

    public WebButton getBotaoAjuda() {
        return botaoAjuda;
    }

    public void setBotaoAjuda(WebButton botaoAjuda) {
        this.botaoAjuda = botaoAjuda;
    }

    public WebButton getBotaoParar() {
        return botaoParar;
    }

    public void setBotaoParar(WebButton botaoParar) {
        this.botaoParar = botaoParar;
    }

    public WebButton getBotaoPasso() {
        return botaoPasso;
    }

    public void setBotaoPasso(WebButton botaoPasso) {
        this.botaoPasso = botaoPasso;
    }

    public WebButton getBotaoPlay() {
        return botaoPlay;
    }

    public void setBotaoPlay(WebButton botaoPlay) {
        this.botaoPlay = botaoPlay;
    }

    public WebButton getBotaoSalvar() {
        return botaoSalvar;
    }

    public void setBotaoSalvar(WebButton botaoSalvar) {
        this.botaoSalvar = botaoSalvar;
    }

    public WebButton getBotaoSalvarComo() {
        return botaoSalvarComo;
    }

    public void setBotaoSalvarComo(WebButton botaoSalvarComo) {
        this.botaoSalvarComo = botaoSalvarComo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoPlay = new com.alee.laf.button.WebButton();
        botaoPasso = new com.alee.laf.button.WebButton();
        botaoParar = new com.alee.laf.button.WebButton();
        botaoSalvar = new com.alee.laf.button.WebButton();
        botaoSalvarComo = new com.alee.laf.button.WebButton();
        botaoAbrir = new com.alee.laf.button.WebButton();
        botaoAjuda = new com.alee.laf.button.WebButton();

        setOpaque(false);

        botaoPlay.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/resultset_next.png"))); // NOI18N
        botaoPlay.setFocusable(false);
        add(botaoPlay);

        botaoPasso.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/step.png"))); // NOI18N
        botaoPasso.setFocusable(false);
        add(botaoPasso);

        botaoParar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/stop.png"))); // NOI18N
        botaoParar.setFocusable(false);
        add(botaoParar);

        botaoSalvar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/save.png"))); // NOI18N
        botaoSalvar.setFocusable(false);
        add(botaoSalvar);

        botaoSalvarComo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoSalvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/save_as.png"))); // NOI18N
        botaoSalvarComo.setFocusable(false);
        add(botaoSalvarComo);

        botaoAbrir.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/folder_closed.png"))); // NOI18N
        botaoAbrir.setFocusable(false);
        add(botaoAbrir);

        botaoAjuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botaoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/Dark/pequeno/helplow.png"))); // NOI18N
        botaoAjuda.setFocusable(false);
        add(botaoAjuda);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAbrir;
    private com.alee.laf.button.WebButton botaoAjuda;
    private com.alee.laf.button.WebButton botaoParar;
    private com.alee.laf.button.WebButton botaoPasso;
    private com.alee.laf.button.WebButton botaoPlay;
    private com.alee.laf.button.WebButton botaoSalvar;
    private com.alee.laf.button.WebButton botaoSalvarComo;
    // End of variables declaration//GEN-END:variables
}
