/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Logo.java
 *
 * Created on 30/09/2011, 00:55:19
 */
package br.univali.ps.ui.imagens;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author fillipipelz
 * @author Luiz Fernando Noschang
 */
public class Logo extends javax.swing.JPanel 
{

    /** Creates new form Logo */
    public Logo() {
        initComponents();
        
        addComponentListener(new ComponentAdapter() 
        {
            @Override
            public void componentShown(ComponentEvent e) 
            {
                // Redimensiona painel para caber o texto do label
                validate(); 
            }            
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portugoStudio = new javax.swing.JLabel();
        lampada = new javax.swing.JLabel();
        versao = new javax.swing.JLabel();

        setOpaque(false);

        portugoStudio.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        portugoStudio.setForeground(new java.awt.Color(255, 255, 255));
        portugoStudio.setText("{PortugolStudio}");

        lampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/grande/light.png"))); // NOI18N

        versao.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        versao.setForeground(new java.awt.Color(255, 255, 153));
        versao.setText("1.01");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(versao))
                    .add(portugoStudio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lampada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(versao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(portugoStudio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(lampada, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lampada;
    private javax.swing.JLabel portugoStudio;
    private javax.swing.JLabel versao;
    // End of variables declaration//GEN-END:variables
}
