/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Logo.java
 *
 * Created on 30/09/2011, 00:55:19
 */
package br.univali.ps.ui.imagens;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author fillipipelz
 * @author Luiz Fernando Noschang
 */
public class Logo extends javax.swing.JPanel 
{

    /** Creates new form Logo */
    public Logo() {
        initComponents();
        
        addComponentListener(new ComponentAdapter() 
        {
            @Override
            public void componentShown(ComponentEvent e) 
            {
                // Redimensiona painel para caber o texto do label
                validate(); 
            }            
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        portugoStudio = new javax.swing.JLabel();
        lampada = new javax.swing.JLabel();
        versao = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        portugoStudio.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        portugoStudio.setForeground(new java.awt.Color(255, 255, 255));
        portugoStudio.setText("{PortugolStudio}");
        add(portugoStudio);
        portugoStudio.setBounds(0, 46, 310, 60);

        lampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ps/ui/icones/grande/light.png"))); // NOI18N
        add(lampada);
        lampada.setBounds(200, 10, 70, 81);

        versao.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        versao.setForeground(new java.awt.Color(255, 255, 153));
        versao.setText("2.0 RC 1");
        add(versao);
        versao.setBounds(10, 10, 60, 40);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lampada;
    private javax.swing.JLabel portugoStudio;
    private javax.swing.JLabel versao;
    // End of variables declaration//GEN-END:variables
}
