/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.ps.depurador;

import br.univali.portugol.nucleo.asa.TipoDado;
import br.univali.portugol.nucleo.depuracao.DepuradorListener;
import br.univali.ps.ui.Aba;
import br.univali.ps.ui.util.IconFactory;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author Carlos A. Krueger
 */
public class AbaDepurador extends Aba implements DepuradorListener
{
     private ATM model;
    /**
     * Creates new form TabelaDepurador
     */
    public AbaDepurador(JTabbedPane container)
    {
        super(container);
        cabecalho.setBotaoFecharVisivel(false);
        cabecalho.setTitulo("Depurador");
        cabecalho.setIcone(IconFactory.createIcon(IconFactory.CAMINHO_ICONES_PEQUENOS, "attributes_display.png"));
        
        initComponents();
        model = new ATM();
        JTable table = new JTable(model);
        //table.setPreferredScrollableViewportSize(new Dimension(500, 70));

        //Create the scroll pane and add the table to it.
        JScrollPane scrollPane = new JScrollPane(table);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    @Override
    public void linhaAtual(int linha)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void simboloDeclarado(String nome, TipoDado tipoDado)
    {
        model.addSimbolo(nome, tipoDado);
    }

    @Override
    public void valorSimboloAlterado(String nome, Object valor)
    {
        model.alteraSimbolo(nome, valor);
    }

    @Override
    public void novaTabelaSimbolos()
    {
         model.resetaTabela();
    }    
}
