/* The following code was generated by JFlex 1.4.1 on 8/8/11 11:45 PM */

/*
 * Generated on 8/9/11 12:00 AM
 */
package br.univali.ps.dominio;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class PortugolLanguage extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 2;
  public static final int YYINITIAL = 0;
  public static final int MLC = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\21\1\10\1\0\1\21\1\17\22\0\1\21\1\43\1\15"+
    "\1\20\1\1\1\47\1\45\1\7\2\44\1\23\1\46\1\42\1\31"+
    "\1\32\1\22\1\4\3\16\4\6\2\3\1\53\1\42\1\66\1\65"+
    "\1\67\1\43\1\20\3\5\1\26\1\30\1\26\5\1\1\25\13\1"+
    "\1\24\2\1\1\44\1\11\1\44\1\70\1\2\1\0\1\36\1\14"+
    "\1\56\1\57\1\35\1\27\1\61\1\50\1\52\2\1\1\37\1\62"+
    "\1\13\1\55\1\51\1\60\1\34\1\40\1\33\1\12\1\63\1\54"+
    "\1\24\1\1\1\64\1\41\1\71\1\41\1\43\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\2\7\1\1\1\7\5\1\1\10\3\7\5\1\3\7"+
    "\1\11\1\12\5\11\1\13\3\11\1\0\1\14\1\2"+
    "\1\15\1\14\1\15\1\14\1\16\1\14\1\3\1\17"+
    "\1\0\1\3\2\1\2\5\1\20\1\21\1\22\7\1"+
    "\1\23\10\1\1\24\11\0\1\15\1\0\2\16\1\3"+
    "\1\25\2\3\1\17\1\3\1\23\1\1\1\5\1\26"+
    "\1\5\25\1\11\0\1\3\1\1\1\5\5\1\1\27"+
    "\12\1\2\0\1\30\2\0\1\31\1\0\1\3\1\1"+
    "\1\5\1\32\12\1\5\0\1\3\1\1\1\5\12\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196"+
    "\0\256\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c"+
    "\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\256\0\256"+
    "\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658"+
    "\0\u0692\0\u06cc\0\u0706\0\256\0\u0740\0\u077a\0\u07b4\0\u07ee"+
    "\0\u0828\0\256\0\u0862\0\u089c\0\u08d6\0\u0910\0\u094a\0\u094a"+
    "\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\256"+
    "\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\256\0\256"+
    "\0\256\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98"+
    "\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68"+
    "\0\u0fa2\0\256\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe"+
    "\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u094a\0\u125a\0\u1294"+
    "\0\256\0\u12ce\0\u1308\0\u0ae0\0\u1342\0\350\0\u137c\0\u13b6"+
    "\0\256\0\u13f0\0\u142a\0\u1464\0\u149e\0\u14d8\0\u1512\0\u154c"+
    "\0\u1586\0\u15c0\0\u15fa\0\u1634\0\u166e\0\u16a8\0\u16e2\0\u171c"+
    "\0\u1756\0\u1790\0\u17ca\0\u1804\0\u183e\0\u1878\0\u18b2\0\u18ec"+
    "\0\u1926\0\u1960\0\u199a\0\u19d4\0\u1a0e\0\u1a48\0\u1a82\0\u1abc"+
    "\0\u1af6\0\u1b30\0\u1b6a\0\u1ba4\0\u1bde\0\u1c18\0\u1c52\0\u1c8c"+
    "\0\350\0\u1cc6\0\u1d00\0\u1d3a\0\u1d74\0\u1dae\0\u1de8\0\u1e22"+
    "\0\u1e5c\0\u1e96\0\u1ed0\0\u1f0a\0\u1f44\0\u1f7e\0\u1fb8\0\u1ff2"+
    "\0\u202c\0\u2066\0\u20a0\0\u20da\0\u2114\0\350\0\u214e\0\u2188"+
    "\0\u21c2\0\u21fc\0\u2236\0\u2270\0\u22aa\0\u22e4\0\u231e\0\u2358"+
    "\0\u2392\0\u1f7e\0\u23cc\0\u202c\0\u2406\0\u2440\0\u247a\0\u24b4"+
    "\0\u24ee\0\u2528\0\u2562\0\u259c\0\u25d6\0\u2610\0\u264a\0\u2684"+
    "\0\u26be\0\u26f8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\5\1\6\1\10\1\11"+
    "\1\4\1\12\1\5\1\13\1\14\1\6\2\4\1\15"+
    "\1\16\1\17\3\5\1\20\1\5\1\21\1\22\1\5"+
    "\1\23\1\24\1\5\1\25\1\26\1\27\1\4\1\30"+
    "\1\27\1\31\1\32\1\17\1\5\1\33\1\34\1\30"+
    "\2\5\1\35\1\36\3\5\1\37\1\5\1\17\1\40"+
    "\1\41\1\30\1\42\10\43\1\44\12\43\1\45\3\43"+
    "\1\46\20\43\1\47\3\43\1\50\15\43\10\51\1\52"+
    "\16\51\1\53\20\51\1\54\3\51\1\55\15\51\73\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\3\5\1\0\11\5\5\0\3\57"+
    "\2\6\1\57\1\6\2\0\4\57\1\0\1\6\1\0"+
    "\1\57\3\0\1\57\1\60\2\61\1\62\1\0\1\63"+
    "\2\57\1\62\1\57\1\60\1\57\7\0\3\57\1\0"+
    "\3\57\1\61\5\57\5\0\3\57\1\64\1\65\1\57"+
    "\1\65\2\0\4\57\1\0\1\65\1\0\1\57\3\0"+
    "\1\66\1\60\2\61\1\62\1\0\1\63\2\57\1\62"+
    "\1\57\1\60\1\57\7\0\3\57\1\0\3\57\1\61"+
    "\5\57\5\0\7\67\1\70\1\71\1\72\60\67\1\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\5\5\1\73\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\2\5\1\74\1\0\11\5\5\0"+
    "\10\14\1\75\1\76\3\14\1\77\54\14\21\0\1\15"+
    "\72\0\1\100\1\101\41\0\1\30\71\0\1\30\5\0"+
    "\6\5\2\0\1\56\1\102\2\5\1\0\1\5\5\0"+
    "\5\5\2\0\3\5\1\103\2\5\7\0\3\5\1\0"+
    "\11\5\36\0\1\30\33\0\1\30\7\0\2\63\1\0"+
    "\1\63\7\0\1\63\54\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\2\5\1\104\3\5"+
    "\7\0\3\5\1\0\11\5\6\0\6\5\2\0\1\56"+
    "\1\5\1\105\1\5\1\0\1\5\5\0\5\5\2\0"+
    "\5\5\1\106\7\0\3\5\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\2\5\1\107\3\5\7\0\3\5\1\0\1\5\1\110"+
    "\7\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\2\5\1\111\3\5\7\0\3\5"+
    "\1\0\11\5\52\0\1\30\72\0\1\30\16\0\1\30"+
    "\5\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\1\5\1\112\1\5\1\113\2\5\7\0"+
    "\3\5\1\0\11\5\6\0\6\5\2\0\1\56\1\5"+
    "\1\114\1\5\1\0\1\5\5\0\5\5\2\0\6\5"+
    "\7\0\3\5\1\0\11\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\3\5\1\115"+
    "\2\5\7\0\3\5\1\0\1\5\1\116\7\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\2\5\1\117\3\5\7\0\3\5\1\0\11\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\2\5\1\120\1\121\2\5\7\0\3\5"+
    "\1\0\11\5\73\0\1\17\72\0\1\17\73\0\1\30"+
    "\10\43\1\0\12\43\1\0\3\43\1\0\20\43\1\0"+
    "\3\43\1\0\15\43\22\0\1\122\102\0\1\123\16\0"+
    "\1\124\52\0\1\125\112\0\1\126\15\0\10\51\1\0"+
    "\16\51\1\0\20\51\1\0\3\51\1\0\15\51\33\0"+
    "\1\127\16\0\1\130\52\0\1\131\112\0\1\132\27\0"+
    "\1\133\57\0\7\57\2\0\4\57\1\0\1\57\1\0"+
    "\1\57\3\0\5\57\2\0\6\57\7\0\3\57\1\0"+
    "\11\57\5\0\3\57\2\134\1\57\1\134\2\0\4\57"+
    "\1\0\1\134\1\0\1\57\3\0\5\57\1\135\1\0"+
    "\6\57\5\0\1\135\1\0\3\57\1\0\11\57\5\0"+
    "\3\57\2\63\1\57\1\63\2\0\4\57\1\0\1\63"+
    "\1\0\1\57\3\0\2\57\2\61\1\62\2\0\2\57"+
    "\1\62\3\57\7\0\3\57\1\0\3\57\1\61\5\57"+
    "\5\0\3\57\2\64\1\57\1\64\2\0\4\57\1\0"+
    "\1\64\1\0\1\57\3\0\2\57\2\61\1\62\1\0"+
    "\1\63\2\57\1\62\3\57\7\0\3\57\1\0\3\57"+
    "\1\61\5\57\5\0\3\57\1\64\1\65\1\57\1\65"+
    "\2\0\4\57\1\0\1\65\1\0\1\57\3\0\1\57"+
    "\1\136\2\61\1\62\1\0\1\63\2\57\1\62\1\57"+
    "\1\136\1\57\7\0\3\57\1\0\3\57\1\61\5\57"+
    "\5\0\3\57\4\137\2\0\3\57\1\137\1\0\1\137"+
    "\1\0\1\57\3\0\2\57\3\137\2\0\2\57\2\137"+
    "\2\57\7\0\3\57\1\0\2\57\2\137\5\57\5\0"+
    "\7\140\1\141\1\0\61\140\7\0\1\141\62\0\4\140"+
    "\1\142\1\140\1\143\1\144\1\0\1\67\1\145\3\67"+
    "\1\142\10\140\1\67\3\140\2\67\35\140\1\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\2\5\1\146\3\5\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\2\5\1\147\1\0\1\5\5\0"+
    "\5\5\2\0\6\5\7\0\3\5\1\0\11\5\5\0"+
    "\11\75\1\150\3\75\1\151\60\75\1\14\1\75\2\14"+
    "\1\0\1\14\1\152\4\14\10\75\1\14\3\75\2\14"+
    "\35\75\1\0\6\5\2\0\1\56\1\5\1\153\1\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\3\5"+
    "\1\0\11\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\4\5\1\154\1\5\7\0"+
    "\3\5\1\0\2\5\1\155\6\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\1\156"+
    "\2\5\1\157\2\5\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\3\5\1\0\4\5\1\160\4\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\6\5\7\0\3\5\1\0\2\5\1\161"+
    "\6\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\6\5\7\0\2\5\1\162\1\0"+
    "\11\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\6\5\7\0\3\5\1\0\5\5"+
    "\1\163\3\5\6\0\6\5\2\0\1\56\1\5\1\164"+
    "\1\5\1\0\1\5\5\0\5\5\2\0\6\5\7\0"+
    "\3\5\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\3\5"+
    "\1\0\1\5\1\165\7\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\1\5\1\166"+
    "\4\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\1\167"+
    "\5\5\7\0\2\5\1\170\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\1\5\1\171\3\5\1\172\7\0\3\5\1\0\3\5"+
    "\1\173\5\5\6\0\6\5\2\0\1\56\1\5\1\174"+
    "\1\5\1\0\1\5\5\0\5\5\2\0\6\5\7\0"+
    "\3\5\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\3\5\1\175\1\5\2\0\6\5"+
    "\7\0\3\5\1\0\11\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\1\5\1\176"+
    "\4\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\6\5"+
    "\7\0\3\5\1\0\10\5\1\177\56\0\1\200\57\0"+
    "\1\201\65\0\1\202\112\0\1\203\66\0\1\204\57\0"+
    "\1\205\65\0\1\206\112\0\1\207\20\0\4\210\5\0"+
    "\1\210\1\0\1\210\7\0\3\210\4\0\2\210\17\0"+
    "\2\210\12\0\3\57\2\134\1\57\1\134\2\0\4\57"+
    "\1\0\1\134\1\0\1\57\3\0\2\57\2\61\1\57"+
    "\2\0\6\57\7\0\3\57\1\0\3\57\1\61\5\57"+
    "\10\0\2\134\1\0\1\134\7\0\1\134\53\0\3\57"+
    "\4\137\2\0\3\57\1\137\1\0\1\137\1\0\1\57"+
    "\3\0\1\57\1\136\3\137\2\0\2\57\2\137\1\136"+
    "\1\57\7\0\3\57\1\0\2\57\2\137\5\57\5\0"+
    "\7\140\1\70\1\0\65\140\1\143\1\140\1\143\1\141"+
    "\1\0\5\140\1\143\57\140\1\67\1\140\1\67\1\141"+
    "\1\0\5\140\1\67\56\140\4\211\1\70\1\0\3\140"+
    "\1\211\1\140\1\211\7\140\3\211\4\140\2\211\17\140"+
    "\2\211\12\140\1\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\4\5\1\212\1\5\7\0"+
    "\3\5\1\0\11\5\5\0\10\75\1\0\64\75\4\213"+
    "\2\75\1\150\2\75\1\213\1\151\1\213\7\75\3\213"+
    "\4\75\2\213\17\75\2\213\12\75\1\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\6\5"+
    "\7\0\3\5\1\0\2\5\1\164\6\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\5\5\1\214\7\0\3\5\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\3\5\1\146\2\5\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\3\5\1\0\1\5\1\215\7\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\4\5\1\146\1\5\7\0\3\5\1\0"+
    "\11\5\6\0\6\5\2\0\1\56\1\216\2\5\1\0"+
    "\1\5\5\0\5\5\2\0\6\5\7\0\3\5\1\0"+
    "\11\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\1\5\1\217\4\5\7\0\3\5"+
    "\1\0\1\5\1\220\7\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\3\5\1\221"+
    "\2\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\6\5"+
    "\7\0\2\5\1\222\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\3\5"+
    "\1\172\2\5\7\0\3\5\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\6\5\7\0\3\5\1\0\5\5\1\223\3\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\2\5\2\146\2\5\7\0\3\5\1\0\11\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\2\5\1\224\3\5\7\0\3\5\1\0"+
    "\11\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\6\5\7\0\3\5\1\0\2\5"+
    "\1\225\6\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\3\5\1\226\2\5\7\0"+
    "\3\5\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\3\5"+
    "\1\0\1\5\1\146\7\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\2\5\1\227"+
    "\3\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\1\230"+
    "\4\5\1\231\7\0\3\5\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\6\5\7\0\2\5\1\232\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\6\5\7\0\3\5\1\0\3\5\1\233\5\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\2\5\1\172\1\0\11\5\60\0"+
    "\1\234\53\0\1\200\105\0\1\235\52\0\1\236\112\0"+
    "\1\237\53\0\1\204\105\0\1\240\52\0\1\241\42\0"+
    "\4\242\5\0\1\242\1\0\1\242\7\0\3\242\4\0"+
    "\2\242\17\0\2\242\12\0\3\140\4\243\1\70\1\0"+
    "\3\140\1\243\1\140\1\243\7\140\3\243\4\140\2\243"+
    "\17\140\2\243\12\140\1\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\2\5"+
    "\1\244\1\0\11\5\5\0\3\75\4\245\2\75\1\150"+
    "\2\75\1\245\1\151\1\245\7\75\3\245\4\75\2\245"+
    "\17\75\2\245\12\75\1\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\3\5"+
    "\1\0\1\5\1\246\7\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\1\5\1\247"+
    "\4\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\3\5"+
    "\1\250\2\5\7\0\3\5\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\2\5\1\251\3\5\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\4\5\1\252\1\5\7\0\3\5\1\0\11\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\6\5\7\0\3\5\1\0\2\5\1\172"+
    "\6\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\1\5\1\253\4\5\7\0\3\5"+
    "\1\0\11\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\6\5\7\0\2\5\1\254"+
    "\1\0\11\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\6\5\7\0\2\5\1\255"+
    "\1\0\11\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\6\5\7\0\3\5\1\0"+
    "\2\5\1\256\6\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\2\5"+
    "\1\155\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\1\5\1\257\4\5"+
    "\7\0\3\5\1\0\11\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\1\146\5\5"+
    "\7\0\3\5\1\0\11\5\6\0\6\5\2\0\1\56"+
    "\1\5\1\155\1\5\1\0\1\5\5\0\5\5\2\0"+
    "\6\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\3\5"+
    "\1\260\2\5\7\0\3\5\1\0\11\5\27\0\1\261"+
    "\107\0\1\200\12\0\1\234\17\0\1\236\1\262\4\236"+
    "\1\262\2\0\3\236\1\0\1\236\1\0\1\262\1\0"+
    "\1\236\1\262\5\236\2\262\6\236\1\0\6\262\3\236"+
    "\1\262\11\236\1\262\26\0\1\263\107\0\1\204\12\0"+
    "\1\237\17\0\1\241\1\264\4\241\1\264\2\0\3\241"+
    "\1\0\1\241\1\0\1\264\1\0\1\241\1\264\5\241"+
    "\2\264\6\241\1\0\6\264\3\241\1\264\11\241\1\264"+
    "\7\0\4\265\5\0\1\265\1\0\1\265\7\0\3\265"+
    "\4\0\2\265\17\0\2\265\12\0\3\140\4\266\1\70"+
    "\1\0\3\140\1\266\1\140\1\266\7\140\3\266\4\140"+
    "\2\266\17\140\2\266\12\140\1\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\6\5\7\0"+
    "\3\5\1\0\1\5\1\267\7\5\5\0\3\75\4\270"+
    "\2\75\1\150\2\75\1\270\1\151\1\270\7\75\3\270"+
    "\4\75\2\270\17\75\2\270\12\75\1\0\6\5\2\0"+
    "\1\56\1\5\1\73\1\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\3\5\1\0\11\5\6\0\6\5"+
    "\2\0\1\56\1\5\1\271\1\5\1\0\1\5\5\0"+
    "\5\5\2\0\6\5\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\6\5\7\0\3\5\1\0\7\5\1\162\1\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\6\5\7\0\1\155\2\5\1\0\11\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\3\5\1\272\2\5\7\0\3\5\1\0"+
    "\11\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\1\5\1\172\4\5\7\0\3\5"+
    "\1\0\11\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\6\5\7\0\3\5\1\0"+
    "\1\5\1\221\7\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\1\273\5\5\7\0"+
    "\3\5\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\3\5\1\274\2\5"+
    "\7\0\3\5\1\0\11\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\6\5\7\0"+
    "\3\5\1\0\3\5\1\275\5\5\27\0\1\236\71\0"+
    "\1\241\52\0\4\5\5\0\1\5\1\0\1\5\7\0"+
    "\3\5\4\0\2\5\17\0\2\5\12\0\3\140\4\67"+
    "\1\70\1\0\3\140\1\67\1\140\1\67\7\140\3\67"+
    "\4\140\2\67\17\140\2\67\12\140\1\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\1\276"+
    "\5\5\7\0\3\5\1\0\11\5\5\0\3\75\4\14"+
    "\2\75\1\150\2\75\1\14\1\151\1\14\7\75\3\14"+
    "\4\75\2\14\17\75\2\14\12\75\1\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\1\172"+
    "\5\5\7\0\3\5\1\0\11\5\6\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\5\5\2\0\6\5"+
    "\7\0\3\5\1\0\6\5\1\155\2\5\6\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\5\5\2\0"+
    "\2\5\1\277\3\5\7\0\3\5\1\0\11\5\6\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\5\5"+
    "\2\0\1\5\1\177\4\5\7\0\3\5\1\0\11\5"+
    "\6\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\5\5\2\0\2\5\1\300\3\5\7\0\3\5\1\0"+
    "\11\5\6\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\5\5\2\0\2\5\1\301\3\5\7\0\3\5"+
    "\1\0\11\5\6\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\5\5\2\0\1\5\1\146\4\5\7\0"+
    "\3\5\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\2\5"+
    "\1\302\1\0\11\5\6\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\5\5\2\0\6\5\7\0\3\5"+
    "\1\0\2\5\1\155\6\5\6\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\5\5\2\0\1\5\1\214"+
    "\4\5\7\0\3\5\1\0\11\5\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10034];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\1\11\15\1\2\11\13\1\1\11"+
    "\5\1\1\11\3\1\1\0\11\1\1\11\1\0\5\1"+
    "\3\11\20\1\1\11\11\0\1\1\1\0\3\1\1\11"+
    "\7\1\1\11\26\1\11\0\23\1\2\0\1\1\2\0"+
    "\1\1\1\0\16\1\5\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public PortugolLanguage() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return null;
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
						case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;

			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new DefaultToken();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PortugolLanguage(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public PortugolLanguage(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { addNullToken(); return firstToken;
          }
        case 27: break;
        case 21: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 28: break;
        case 18: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 29: break;
        case 6: 
          { addToken(Token.WHITESPACE);
          }
        case 30: break;
        case 14: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 31: break;
        case 22: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 32: break;
        case 13: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 33: break;
        case 19: 
          { addToken(Token.RESERVED_WORD);
          }
        case 34: break;
        case 8: 
          { addToken(Token.SEPARATOR);
          }
        case 35: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 36: break;
        case 11: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 37: break;
        case 17: 
          { start = zzMarkedPos-2; yybegin(EOL_COMMENT);
          }
        case 38: break;
        case 23: 
          { addToken(Token.FUNCTION);
          }
        case 39: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 40: break;
        case 5: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 41: break;
        case 26: 
          { addToken(Token.DATA_TYPE);
          }
        case 42: break;
        case 20: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 43: break;
        case 15: 
          { addToken(Token.ERROR_CHAR);
          }
        case 44: break;
        case 16: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 45: break;
        case 25: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 46: break;
        case 24: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 47: break;
        case 12: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 48: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 49: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 50: break;
        case 9: 
          { 
          }
        case 51: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 52: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 195: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 196: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 197: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
